"""added coupon and currency type columns

Revision ID: 083a065d5e92
Revises: 8c9e339bf461
Create Date: 2026-03-28 15:40:59.234479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '083a065d5e92'
down_revision = '8c9e339bf461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    coupon_type_enum = sa.Enum('DISCOUNT', 'VOUCHER', name='coupontype')
    currency_enum = sa.Enum('ILS', 'USD', 'EUR', name='currency')
    coupon_type_enum.create(op.get_bind(), checkfirst=True)
    currency_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'coupon',
        sa.Column('coupon_type', coupon_type_enum, nullable=True, server_default='DISCOUNT'),
    )
    op.add_column('coupon', sa.Column('initial_value', sa.Float(), nullable=True))
    op.add_column('coupon', sa.Column('current_value', sa.Float(), nullable=True))
    op.add_column('coupon', sa.Column('currency', currency_enum, nullable=True))
    op.execute("UPDATE coupon SET coupon_type = 'DISCOUNT' WHERE coupon_type IS NULL")
    op.alter_column('coupon', 'coupon_type', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'currency')
    op.drop_column('coupon', 'current_value')
    op.drop_column('coupon', 'initial_value')
    op.drop_column('coupon', 'coupon_type')
    currency_enum = sa.Enum('ILS', 'USD', 'EUR', name='currency')
    coupon_type_enum = sa.Enum('DISCOUNT', 'VOUCHER', name='coupontype')
    currency_enum.drop(op.get_bind(), checkfirst=True)
    coupon_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
